name: apps_food
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6  # tambahkan dependensi GetX
  cupertino_icons: ^1.0.8  # hanya satu kali
  shared_preferences: ^2.0.10 
  sqflite: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/title.png
    - assets/profile.jpeg
    - assets/cafe.jpeg
    - assets/esteh.jpg
    - assets/fedchiken.jpeg
    - assets/pozza.jpg
    - assets/shawarma.jpeg
    - assets/bakso.jpeg
    - assets/burger.jpeg
    - assets/dimsum.jpeg
    - assets/pasta.jpeg
    - assets/ramen.jpeg
    - assets/steakhouse.jpeg
    - assets/sushi.jpeg